### ISSUE TITLE
Error in panel Closure::__invoke

### ISSUE THREAD

**Issue by Lexinek** [TomasVotruba/nette-single-action-presenter#10]
Please see screenshot. It is really easy to reproduce, just force error presenter on any page that is using this package (example is on screenshot, the most easy way).

<img width="1680" alt="screenshot 2017-03-21 17 35 44" src="https://cloud.githubusercontent.com/assets/3995003/24158545/e909d142-0e5c-11e7-81ed-17bb610201d1.png">

**Comment by TomasVotruba** [comment]
I see the output. Thanks for the screenshot!

What is the desired behavior?

**Comment by Lexinek** [comment]
No error in tracy? I don't know, what do you think?
Maybe this is fine, i just had the feelings like: Oh no, there is error in my tracy, something must be wrong and it has to be fixed.

**Comment by TomasVotruba** [comment]
I got lost in yesterdays issues, that's why I asked. I understand now. Will check it.

**Comment by TomasVotruba** [comment]
I guess it's resolved for 2.0!

Thanks for reporting

![image](https://user-images.githubusercontent.com/924196/27297507-62cad878-5525-11e7-86f9-8fc7cd11ce00.png)
