### ISSUE TITLE
Calling parent::run() in HomepagePresenter::run()

### ISSUE THREAD

**Issue by Lexinek** [TomasVotruba/nette-single-action-presenter#2]
There is alot of useful code in `UI\Presenter::run`, imho having some simpler version of that in `BasePresenter` or just calling `parent::run($request)` would be useful

**Comment by TomasVotruba** [comment]
The goal is to get rid of `Presenter` vendor lock.

What do you need from there `run()` method??

**Comment by Lexinek** [comment]
I will write what things are useful for me (single action presenter for rest api, no templates):

Very useful for me i see `canonicalize()` which can not be used without
```php
$this->request = $request;
```

As i have some structure - extending SecuredPresenter where check for jwt is present, it would not work without this:
```php
$this->checkRequirements($this->getReflection());
$this->startup();
```

And of course:
```php
$this->onShutdown($this, $this->response);
$this->shutdown($this->response);
```

Well, it is not much, but these are real dependencies for me that i need in every presenter.

**Comment by Lexinek** [comment]
Sry, missclicked to `close and comment` :-)

**Comment by TomasVotruba** [comment]
@Lexinek No problem. I do this even for PRs ;)

**Comment by TomasVotruba** [comment]
How do you you `canonicalize()` exactly?

Those you mentioned are simply events. Can be decoupled to EventDispatcher (on background).

Also, security should not depend on presenter run nor presenter name. `checkRequirements` is very limited, useless in practice.

```php
$this->checkRequirements($this->getReflection());
$this->startup();
$this->onShutdown($this, $this->response);
$this->shutdown($this->response);
```

Anything else?

**Comment by Lexinek** [comment]
Right now im just extending `Nette\Application\UI\Presenter` and calling `parent::run()`.
Haha, i just realized that in case of rest api i do not really need that `canonicalize()` call.

About the events, what is the way you would suggest to do it? I know some packages are dependent on presenter events (https://github.com/Symplify/SymfonyEventDispatcher/blob/master/src/Adapter/Nette/Event/PresenterShutdownEvent.php).

I went through the default `run()` implementation and for my use case there are a lot of useless things working with ajax+template that i do not need.

> Also, security should not depend on presenter run nor presenter name. checkRequirements is very limited, useless in practice.

Thanks, it makes me think about my application layer and it's design might not be good!

**Comment by TomasVotruba** [comment]
@Lexinek Just gimme a sec, I will show you in a PR I'm making now.

**Comment by Lexinek** [comment]
I think this one is not relevant anymore, since final presenters are using `__invoke()` and not `run()`

**Comment by TomasVotruba** [comment]
I see, I totally forgot about this. Let's close it than.

Thank you
