### ISSUE TITLE
Release as composer package

### ISSUE THREAD

**Issue by Lexinek** [TomasVotruba/nette-single-action-presenter#5]
We would love to use this in our project ;).

**Comment by Lexinek** [comment]
Bump.

I would like to set this as dependency for odbav-to/presenter-route

**Comment by TomasVotruba** [comment]
Done, thanks for the package!
https://packagist.org/packages/symplify/symbiotic-controller

**Comment by TomasVotruba** [comment]
I will try it in my lecture in a sec :)
